empTransformDBT:
  outputs:
    raw:
      account: lj38754.central-india.azure
      database: mydb
      password: XDgczKW5nRYVj75
      role: poc_role
      schema: raw
      threads: 1
      type: snowflake
      user: saipranay
      warehouse: compute_wh
    transform:
      account: lj38754.central-india.azure
      database: mydb
      password: XDgczKW5nRYVj75
      role: poc_role
      schema: transform
      threads: 1
      type: snowflake
      user: saipranay
      warehouse: compute_wh

  target: raw
