version: 2


sources:
  - name: emp_source
    database: mydb
    schema: raw
    tables:     
      - name: emp
        columns:
          - name: Password
            meta:
              masking_policy: password_mask

models:
  - name: emp
    description: Staged customer data from jaffle_shop app
    columns:
      - name: password
        meta:
          masking_policy: password_mask
